### ISSUE TITLE
Extract coefficients with sign

### ISSUE THREAD

**Issue by Rishikesh-kumar-7258** [Rishikesh-kumar-7258/calculator#1]
# react-version
The current code is able to extract all the coefficients from an equation even if the coefficient is not present as in the case of `x+y=0` and if the variable is supposed to be present and its coefficient is 0 as in the case of `x=5`.

The current code is using the ***regex*** expression to clean the equation and extract variables. 
Code should be able to extract the coefficients with signs.

**Comment by RubenSmn** [comment]
Hi @Rishikesh-kumar-7258 I had some trouble when using the Equation Solver. I did some console logging and noticed that the temp value returning from `list_from_equation` is a `NaN` if the equation is `x=5`.

I came up with a simple regex `/[\d]+(?=[a-z])|\b(?=[a-z])/g` which gets all the numbers in front of an `a...z` character. If there is no number in front this matches `null`. You could use this to check if the match is `null` and then simple add a `1` to your matrix.

I hope I was of some help!

**Comment by Rishikesh-kumar-7258** [comment]
Hello @RubenSmn thank you for pointing it out. Actually, it was the previous implementation that you have seen. The current one which I am working on is in another branch `react-version`. The previous one has some bugs I am aware of that.

**Comment by Rishikesh-kumar-7258** [comment]
## solved
This issue has been solved that's why I am closing this issue
